- hosts: webservers
  vars:
    nginx_port: 8080
    root_dir: /usr/share/nginx/html 
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
      become: yes

    - name: update nginx config
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

    - name: copy html
      ansible.builtin.copy:
        src: files/index.html
        dest: 
          "{{ root_dir }}/index.html"
      become: yes


  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes

