- hosts: webservers
  vars:
    nginx_port: 8080
    root_dir: /usr/share/nginx/html 
    welcome_text: "This is server {{ server_name }}!"
  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name: 
          - nginx
          - cowsay
        state: latest
      become: yes

    - ansible.builtin.shell: cowsay "This is {{ server_name }}"
      register: cowsay_result

    - name: update nginx config
      ansible.builtin.template: 
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

    - name: copy html
      ansible.builtin.template:
        src: files/index.html
        dest: 
          "{{ root_dir }}/index.html"
      become: yes


  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes

